### ISSUE TITLE
Text overlapping on smaller width size

### ISSUE THREAD

**Issue by zomeru** [joshxfi/portfolio-next#1]
Some text are overlapping and overflowing in smaller width sizes between 768px and 1080px.

![1](https://user-images.githubusercontent.com/19688908/128689028-7f8f7ae9-40cc-431f-81fb-22d318b60647.PNG)
![2](https://user-images.githubusercontent.com/19688908/128689034-e477364b-a11a-406c-92c9-3185fa225dc6.PNG)
![3](https://user-images.githubusercontent.com/19688908/128689037-3fa8896c-8a0a-4b74-8cfa-7216a59d08aa.PNG)

**Comment by joshxfi** [comment]
Thanks! fixed by changing breakpoint to 1080px -> 0e95345

**Comment by joshxfi** [comment]
closing this issue! thanks!
