### ISSUE TITLE
Layout too stretch in wide screen

### ISSUE THREAD

**Issue by zomeru** [joshxfi/portfolio-next#2]
You might want to add a max-width on your layout because it's too stretched on wide screen display.

![i1](https://user-images.githubusercontent.com/19688908/129097413-4012f127-61be-4d7a-9b16-bdd298a4367e.PNG)
![i2](https://user-images.githubusercontent.com/19688908/129097420-c83906f2-37d9-424d-9364-bcc28ded79c8.PNG)

**Comment by joshxfi** [comment]
I was using `80%` as my `container` for my layout, I guess it doesn't work well on larger screens. Thanks for this issue! I'll work on it later.

**Comment by joshxfi** [comment]
Fixed! f0e65d55122716765fe9aab8dca139977cfa4e8f , thanks! Closing this issue...
